version: "2"
services:
  ts2wasm-web:
    platform: linux/amd64
    container_name: ts2wasm-web
    build:
      context: ./portal
      dockerfile: Dockerfile
      args:
        - SERVER_IP=${SERVER_IP}
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${WEB_PORT}:80
    environment:
      - "TZ=Asia/Shanghai"
    restart: on-failure
  ts2wasm-server:
    platform: linux/amd64
    container_name: ts2wasm-server
    build:
      context: ../..
      dockerfile: ./tools/playground/server/Dockerfile
    ports:
      - ${SERVER_PORT}:3001
    volumes:
      - ts2wasm-data:/root/.ts2wasm_playground
    # environment:
      # - DOCKER_HOST=tcp://docker:2376
      # - DOCKER_CERT_PATH=/certs/client
      # - DOCKER_TLS_VERIFY=1
    restart: on-failure

volumes:
  ts2wasm-data: {}
