(module
  (type $ft (func))
  (type $st (struct))
  (type $at (array i8))

  (table 10 anyref)

  (elem declare func $f)
  (func $f)

  (func (export "init") (param $x externref)
    (table.set (i32.const 0) (ref.null any))
    (table.set (i32.const 1) (i31.new (i32.const 7)))
    (table.set (i32.const 2) (struct.new_canon_default $st))
    (table.set (i32.const 3) (array.new_canon_default $at (i32.const 0)))
    (table.set (i32.const 4) (extern.internalize (local.get $x)))
    (table.set (i32.const 5) (ref.null i31))
    (table.set (i32.const 6) (ref.null struct))
    (table.set (i32.const 7) (ref.null none))
  )

  (func (export "ref_cast_non_null") (param $i i32)
    (drop (ref.as_non_null (table.get (local.get $i))))
    (drop (ref.cast null any (table.get (local.get $i))))
  )
  (func (export "ref_cast_null") (param $i i32)
    (drop (ref.cast null any (table.get (local.get $i))))
    (drop (ref.cast null struct (table.get (local.get $i))))
    (drop (ref.cast null array (table.get (local.get $i))))
    (drop (ref.cast null i31 (table.get (local.get $i))))
    (drop (ref.cast null none (table.get (local.get $i))))
  )
  (func (export "ref_cast_i31") (param $i i32)
    (drop (ref.cast i31 (table.get (local.get $i))))
    (drop (ref.cast null i31 (table.get (local.get $i))))
  )
  (func (export "ref_cast_struct") (param $i i32)
    (drop (ref.cast struct (table.get (local.get $i))))
    (drop (ref.cast null struct (table.get (local.get $i))))
  )
  (func (export "ref_cast_array") (param $i i32)
    (drop (ref.cast array (table.get (local.get $i))))
    (drop (ref.cast null array (table.get (local.get $i))))
  )
)

