from building import *

cwd     = GetCurrentDir()

src = Split('''
thread_manager.c
''')

CPPPATH = [cwd]

group = DefineGroup('iwasm_lib_thread_mgr', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
