# Copyright (C) 2023 Liquid Reply GmbH. All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[package]
name = "wamr-sys"
description = "WAMR is a lightweight standalone WebAssembly (Wasm) runtime with small footprint, high performance and highly configurable features"
version = "0.1.0"
license.workspace = true
links = "vmlib"
categories = ["api-bindings", "wasm"]
keywords =["api-bindings", "wasm", "webassembly"]
repository = "https://github.com/bytecodealliance/wasm-micro-runtime"
edition.workspace = true

[dependencies]

[build-dependencies]
cc = "1.0"
cmake = "0.1"
bindgen = "0.66"

[features]
llvmjit = []
