[package]
name = "wamr_rust_sdk"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"


[dependencies]
wamr-sys = {path = "crates/wamr-sys", version = "0.1.0}

[workspace]
members = ["crates/wamr-sys"]

