[package]
name = "wamr-rust-sdk"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
exclude = ["examples/"]

[dependencies]
wamr-sys = { path = "crates/wamr-sys", version = "0.1.0" }

[workspace]
members = ["crates/wamr-sys"]
