from building import *

cwd     = GetCurrentDir()

#src = Split('''
#libc_builtin_wrapper.c
#''')

src = Glob('*.c')

CPPDEFINES = ['WASM_ENABLE_LIBC_BUILTIN=1']

CPPPATH = [cwd]


group = DefineGroup('iwasm_libc_builtin', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
